"""Consistency tests for the pre-computed rollup tables.

These check that the rollups generated by scripts/generate_data.py and
loaded into Supabase are internally consistent (the math agrees with the
raw tables and with our metric tools). Catches regressions in either the
generator or the metric definitions.

Run with:
    uv run pytest tests/test_rollups.py -v
"""

from __future__ import annotations

from tools.metrics import get_metric
from tools.sql import query_database


def _column(rows: list[list], idx: int):
    return [r[idx] for r in rows]


def test_monthly_metrics_has_24_months():
    r = query_database("SELECT COUNT(*) FROM monthly_metrics")
    assert r["error"] is None
    assert r["rows"][0][0] == 24


def test_arr_equals_mrr_end_times_12():
    r = query_database("SELECT month, mrr_end, arr FROM monthly_metrics ORDER BY month")
    assert r["error"] is None
    for month, mrr_end, arr in r["rows"]:
        # NUMERIC columns come back as float via our _to_json_safe helper.
        assert abs(arr - mrr_end * 12) < 0.5, f"{month}: arr={arr} != mrr_end*12={mrr_end * 12}"


def test_mom_growth_pct_is_consistent_with_mrr_endpoints():
    """mom_growth_pct should equal (mrr_end - mrr_start) / mrr_start * 100."""
    r = query_database(
        "SELECT month, mrr_start, mrr_end, mom_growth_pct FROM monthly_metrics "
        "WHERE mrr_start > 0 ORDER BY month"
    )
    assert r["error"] is None
    for month, mrr_start, mrr_end, mom in r["rows"]:
        expected = (mrr_end - mrr_start) / mrr_start * 100
        assert abs(mom - expected) < 0.05, (
            f"{month}: mom_growth_pct={mom} but expected {expected:.2f}"
        )


def test_arpu_is_consistent_with_mrr_end_and_paying_customers():
    r = query_database(
        "SELECT month, mrr_end, paying_customers, arpu FROM monthly_metrics "
        "WHERE paying_customers > 0 ORDER BY month"
    )
    assert r["error"] is None
    for month, mrr_end, paying, arpu in r["rows"]:
        expected = mrr_end / paying
        assert abs(arpu - expected) < 0.05, f"{month}: arpu={arpu} but expected {expected:.2f}"


def test_get_metric_mrr_matches_monthly_metrics():
    """The get_metric tool and the underlying table should always agree."""
    direct = query_database("SELECT month, mrr_end FROM monthly_metrics ORDER BY month")
    via_tool = get_metric("mrr")
    assert via_tool["error"] is None
    assert len(via_tool["points"]) == len(direct["rows"])
    for point, (month, mrr) in zip(via_tool["points"], direct["rows"], strict=True):
        assert point["month"] == month
        assert abs((point["value"] or 0) - mrr) < 0.01


def test_outage_month_has_elevated_gross_churn():
    """Planted pattern: March 2026 outage should produce a churn spike."""
    r = query_database(
        "SELECT month, gross_churn_rate FROM monthly_metrics "
        "WHERE month IN ('2026-02', '2026-03') ORDER BY month"
    )
    assert r["error"] is None
    by_month = dict(r["rows"])
    assert by_month["2026-03"] > by_month["2026-02"] * 2, f"expected outage spike: {by_month}"


def test_pro_price_hike_month_has_elevated_gross_churn():
    """Planted pattern: May 2025 (Pro price hike) should produce a churn spike."""
    r = query_database(
        "SELECT month, gross_churn_rate FROM monthly_metrics "
        "WHERE month IN ('2025-04', '2025-05') ORDER BY month"
    )
    assert r["error"] is None
    by_month = dict(r["rows"])
    assert by_month["2025-05"] > by_month["2025-04"] * 2, (
        f"expected price-hike churn spike: {by_month}"
    )
